#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/autologin

start_service() {
	local enabled username password domain server
	
	config_load autologin
	config_get enabled config enabled 0
	
	[ "$enabled" = "1" ] || return 0
	
	config_get username config username
	config_get password config password
	config_get domain config domain ""
	config_get server config server "172.26.8.11"
	
	[ -n "$username" ] && [ -n "$password" ] || {
		echo "Username or password not configured"
		return 1
	}
	
	procd_open_instance
	procd_set_param command $PROG "$username" "$password" "$domain" "$server"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}